---
- name: Write a simple file.
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Write a file.
      ansible.builtin.lineinfile:
        path: test.txt
        line: hiiii
        create: true